spring.application.name=ingredient
#spring.datasource.url=jdbc:postgresql://localhost:5432/ingredientdb
#spring.datasource.username=christian
#spring.datasource.password=092MLBOA
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.sql.init.mode=always

db.url=jdbc:postgresql://localhost:5432/ingredientdb
db.user=christian
db.password=092MLBOA