spring.application.name=ingredient
spring.datasource.url=jdbc:postgresql://localhost:5432/ingredientDB
spring.datasource.username=Christian
spring.datasource.password=092MLBOA*
spring.datasource.driver-class-name=org.postgresql.Driver 
